# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: windows-latest

variables:
- name: aria_at_ref
  value: main
- name: browser
  value: chrome
- name: nvda_version
  value: 'latest'
- name: test_pattern
  value: '{reference/**,test-*-nvda.*}'
- name: work_dir
  value: 'tests/alert'
- name: callback_header
  value: ''
- name: callback_url
  value: ''
- name: status_url
  value: ''

steps:
# List of azure tasks
# https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/?view=azure-pipelines&viewFallbackFrom=azure-devops
- task: UseNode@1
  displayName: Install Node
  inputs:
    version: '20.x'
- task: GoTool@0
  displayName: Install Go
  inputs:
    version: '1.10'
